import { useState } from 'react';
import { ArrowRight, Bookmark, Check, ChevronRight, ClipboardList, Minus, Plus, Share2, Trash2, Wallet } from 'lucide-react';
import { Dialog, EmptyState } from './components';
import { type RestaurantMenu, type Venue } from './data';
import { currentDish, useFoodTools } from './foodTools';
import { useI18n } from './i18n';
import { MenuItemThumb } from './MenuItemThumb';

export function SavedDishes({ menus, venues, onOpen }: { menus: Record<string, RestaurantMenu>; venues: Venue[]; onOpen: (venue: Venue) => void }) {
  const tools = useFoodTools(); const { t, n, lang } = useI18n();
  return tools.saved.length ? <div className="saved-dishes-list">{tools.saved.map(reference => {
    const live = currentDish(reference, menus); const item = live || reference.item; const venue = venues.find(v => v.id === reference.venueId);
    return <article className="saved-dish-row" key={reference.key}><MenuItemThumb src={item.imageUrl} alt={item.name} /><div><h3>{lang === 'ar' && item.nameAr ? item.nameAr : item.name}</h3><p>{reference.venueName} {live ? '' : ` / ${t('Not in the current menu', 'غير موجود في المنيو الحالي')}`}</p><strong>{live?.price !== null && live?.price !== undefined ? `${n(live.price)} ${t('EGP', 'ج.م')}` : t('Price needs checking', 'السعر يحتاج تأكيد')}</strong></div><div className="saved-dish-actions"><button className="icon-button" onClick={() => tools.removeSaved(reference.key)} aria-label={t('Remove saved dish', 'حذف الطبق المحفوظ')}><Bookmark size={17} fill="currentColor" /></button><button className="button button-outline button-small" disabled={!live || !venue} onClick={() => { if (live && venue) tools.addToPlan(venue, live); }}><Plus size={13} />{t('Plan', 'أضف للخطة')}</button>{venue && <button className="icon-button" onClick={() => onOpen(venue)} aria-label={t('View menu')}><ChevronRight size={16} /></button>}</div></article>;
  })}</div> : <EmptyState icon={<Bookmark size={28} />} title={t('Keep your go-to dishes close.', 'احتفظ بأطباقك المفضلة.')} description={t('Bookmark a dish inside any menu. Saved dishes stay on this device, with a link back to their source.', 'احفظ أي طبق من المنيو. الأطباق بتفضل على جهازك مع رابط لمصدرها.')} />;
}

export function FoodPlannerDialog({ menus, venues, onClose, onOpen }: { menus: Record<string, RestaurantMenu>; venues: Venue[]; onClose: () => void; onOpen: (venue: Venue) => void }) {
  const tools = useFoodTools(); const { t, n, lang } = useI18n(); const [message, setMessage] = useState(''); const [confirmClear, setConfirmClear] = useState(false);
  const rows = tools.plan.map(reference => ({ reference, current: currentDish(reference, menus) }));
  const unknown = rows.filter(row => !row.current || row.current.price === null).length;
  const total = Math.round(rows.reduce((sum, row) => sum + (row.current?.price || 0) * row.reference.quantity, 0) * 100) / 100;
  const difference = Math.round((tools.budget - total) * 100) / 100;
  const share = async () => {
    const text = [t('My campus meal plan', 'خطة أكلي في الجامعة'), ...rows.map(({ reference, current }) => `${reference.quantity} x ${reference.item.name} / ${reference.venueName} / ${current?.price === null || !current ? t('Ask in store') : `${current.price * reference.quantity} EGP`}`), `${t('Known subtotal', 'مجموع الأسعار المعروفة')}: ${total} EGP`, t('Planning only, not an order. Confirm prices in store.', 'خطة فقط، مش طلب. تأكد من الأسعار في المحل.')].join('\n');
    try { if (navigator.share) await navigator.share({ title: 'CS Family Star', text }); else { await navigator.clipboard.writeText(text); setMessage(t('Plan copied.', 'تم نسخ الخطة.')); } } catch (err) { if ((err as Error).name !== 'AbortError') setMessage(t('Sharing is unavailable in this browser.', 'المشاركة غير متاحة في المتصفح.')); }
  };
  return <Dialog title={t('Meal budget planner', 'خطط وجبتك وميزانيتك')} onClose={onClose} className="planner-dialog"><div className="dialog-body"><p className="muted">{t('Build a lunch plan from real menu items. This is a shortlist, not a food order.', 'خطط الغدا من أطباق المنيو. دي قائمة تخطيط، مش طلب أكل.')}</p><label className="field-label planner-budget">{t('Your total budget', 'ميزانيتك الإجمالية')}<div className="input-unit"><input type="number" min={1} max={100000} step="0.01" value={tools.budget} onChange={e => tools.setBudget(Number(e.target.value))} /><span>{t('EGP', 'ج.م')}</span></div></label>{rows.length ? <><div className="planner-items">{rows.map(({ reference, current }) => {
    const item = current || reference.item; const venue = venues.find(v => v.id === reference.venueId); const priceChanged = current && current.price !== reference.item.price;
    return <article className="planner-item" key={reference.key}><MenuItemThumb src={item.imageUrl} alt={item.name} /><div className="planner-item-copy"><h3>{lang === 'ar' && item.nameAr ? item.nameAr : item.name}</h3><button className="text-button" disabled={!venue} onClick={() => { if (venue) onOpen(venue); }}>{reference.venueName}<ArrowRight size={11} /></button>{!current && <p className="planner-warning">{t('Not in the current menu. Price excluded.', 'غير موجود في المنيو الحالي. السعر غير محسوب.')}</p>}{current?.price === null && <p className="planner-warning">{t('No fixed price. Subtotal is incomplete.', 'بدون سعر ثابت. المجموع غير مكتمل.')}</p>}{priceChanged && <p className="planner-warning">{t('Price changed since you added this dish.', 'السعر اتغير من وقت إضافة الطبق.')}</p>}<div className="quantity-control"><button onClick={() => tools.setQuantity(reference.key, reference.quantity - 1)} aria-label={t('Decrease quantity', 'تقليل الكمية')}><Minus size={14} /></button><span>{n(reference.quantity)}</span><button disabled={reference.quantity >= 20} onClick={() => tools.setQuantity(reference.key, reference.quantity + 1)} aria-label={t('Increase quantity', 'زيادة الكمية')}><Plus size={14} /></button></div></div><div className="planner-price"><strong>{current && current.price !== null ? n(Math.round(current.price * reference.quantity * 100) / 100) : '--'}</strong><small>{t('EGP', 'ج.م')}</small><button className="icon-button" onClick={() => tools.setQuantity(reference.key, 0)} aria-label={t('Remove dish', 'حذف الطبق')}><Trash2 size={14} /></button></div></article>;
  })}</div><div className="planner-total"><span>{unknown ? t('Known subtotal', 'مجموع الأسعار المعروفة') : t('Menu subtotal', 'مجموع أسعار المنيو')}</span><strong>{n(total)} <small>{t('EGP', 'ج.م')}</small></strong></div><p className={`planner-balance ${difference < 0 ? 'over-budget' : ''}`}><Wallet size={15} />{difference < 0 ? `${n(Math.abs(difference))} ${t('EGP over budget', 'ج.م فوق الميزانية')}` : `${n(difference)} ${t('EGP left in your budget', 'ج.م متبقية من الميزانية')}`}{unknown > 0 && ` / ${n(unknown)} ${t('unpriced items', 'صنف بدون سعر')}`}</p><p className="notice-text">{t('Taxes, service fees, substitutions, and live availability are not included. Brand-menu prices can differ at the campus branch.', 'الضرائب والخدمة والتغييرات والتوفر الحالي غير محسوبة. أسعار منيو العلامة ممكن تختلف في فرع الجامعة.')}</p><div className="planner-actions"><button className="text-button" onClick={() => { if (confirmClear) { tools.clearPlan(); setConfirmClear(false); } else setConfirmClear(true); }}>{confirmClear ? t('Confirm clear plan', 'أكد مسح الخطة') : t('Clear plan', 'امسح الخطة')}<Trash2 size={13} /></button><button className="button button-primary" onClick={() => void share()}><Share2 size={16} />{t('Share plan', 'شارك الخطة')}</button></div></> : <EmptyState icon={<ClipboardList size={30} />} title={t('A good lunch starts with a little plan.', 'الغدا الحلو بيبدأ بخطة صغيرة.')} description={t('Use the plus button beside a dish to add it here. Set quantities and see what fits your budget.', 'اضغط علامة زائد جنب أي طبق لإضافته هنا. حدد الكمية وشوف إيه يناسب ميزانيتك.')} />}{message && <p className="inline-success" role="status"><Check size={14} />{message}</p>}</div></Dialog>;
}